# Define all interfaces
WIFI_IFACE="wlx000"
CABLE_IFACE="enp0s2"
WAN_IFACE="wlp2s0"
MODULE_NAME="rt2800usb"

# Define HOT SPOT
HOT_SPOT="iPhone"
HOT_SPOT_PASS='Pass_for_HotSpot'

# Define SSID and password for the Wi-Fi network
SSID="Client_SSID"
WIFI_PASS=Client_SSID_strong_pass
CHANNEL=10

# Define WiFi settings and leases
GATEWAY_IP="10.10.10.1"
NETMASK="255.255.255.0"
DHCP_RANGE_START="10.10.10.10"
DHCP_RANGE_END="10.10.10.20"

# Static DHCP Leases (MAC,Hostname,IP)
# Devices with static IP addresses
client_name="client_1"
client_ip="10.10.10.21"
client_mac="11:22:33:ff:aa:88"

client2_name="client2"
client2_ip="10.10.10.22"
client2_mac="11:22:33:ff:aa:88"

cam1_name="cam_1"
cam1_ip="10.10.10.23"
cam1_mac="11:22:33:ff:aa:88"

cam2_name="cam_2"
cam2_ip="10.10.10.24"
cam2_mac="11:22:33:ff:aa:88"

cam3_name="cam_3"
cam3_ip="10.10.10.25"
cam3_mac="11:22:33:ff:aa:88"

# Static DHCP Leases
LEASE_1="$client_mac,$client_name,$client_ip"
LEASE_2="$client2_mac,$client2_name,$client2_ip"
LEASE_3="$cam1_mac,$cam1_name,$cam1_ip"
LEASE_4="$cam2_mac,$cam2_name,$cam2_ip"
LEASE_5="$cam3_mac,$cam3_name,$cam3_ip"
