# === USER1 User /* It is a SYSTEM USER */ ::
USERNAME_USER1=suser
USER_ID_USER1=2200
USER_GID_USER1=2200

# === USER2 User /* Regular USER - created during the installation process*/ ::
USERNAME_USER2=ruser

# Network
# ====================
CABLE_IFACE=enp0
IFACE_MAC=en
WIFI_IFACE=wlx00
WAN_IFACE=wlp0s0

IP_PREFIX="10.10.10."
# The path to the udev rules file
RULES_FILE="/etc/udev/rules.d/10-network.rules"
SERVICE_IP="10.10.10.100"
NETMASK="255.255.255.0"
GATEWAY="10.10.10.1"
DNS1="8.8.8.8" 
DNS2="1.1.1.1"

# App settings
WG_PORT=51820

# Val
APPLY_CHANGES=true
DOCKER_ENG=true